core/camera/urls.py
from camera import views
from django.urls import path,include

app_name = 'camera'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),

    path('camera_feed/',views.camera_feed, name='camera_feed'),
    path('face_detect/',views.face_detect, name='face_detect'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from camera import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    
    path('detect_on/',views.detect_on, name='detect_on'),

    path('login_succsess/',views.login_succsess,name='login_succsess'),
    path('camera/',include('camera.urls')),
    path('logout/', views.user_logout, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/camera/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    user_pic = models.ImageField(upload_to='user_pic',blank=True)
    
    def __str__(self):
        return self.user.username

core/camera/forms.py
from django import forms
from camera.models import UserProfile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('user_pic',)

core/camera/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse,StreamingHttpResponse,HttpResponseServerError
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators import gzip
from django.contrib import messages
from django.conf import settings
from camera.forms import UserForm,UserProfileInfoForm
from camera.opencv import VideoCamera, FaceDetect
import numpy as np
import face_recognition, os, cv2, glob
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    return render(request,'camera/index.html')
    
@login_required
def detect_on(request):
    return render(request,'camera/face_detect.html')

@login_required
def login_succsess(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'user_pic' in request.FILES:
                print('found it')
                profile.user_pic = request.FILES['user_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'camera/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")

    else:
        return render(request, 'camera/login.html', {})


def generator1(camera):
    while True:
        frame = camera.get_frame()
        yield(b'--frame\r\n'
        b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

def generator2(camera):
    while True:
        frame = camera.get_frame()
        yield(b'--frame\r\n'
        b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

@gzip.gzip_page
def camera_feed(request):
    return StreamingHttpResponse(generator1(VideoCamera()),content_type="multipart/x-mixed-replace;boundary=frame")

@gzip.gzip_page
def face_detect(request):
    return StreamingHttpResponse(generator2(FaceDetect()),content_type="multipart/x-mixed-replace;boundary=frame")

core/camera/templates/camera/face_detect.html
{% extends "camera/sidebar.html" %}
{% block body_block %}
<br>
<div class="container">
    <div class="card text-center">
        {% if user.is_authenticated %}
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index'%}">Vanilla Feed</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#">AI Feed 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1">AI Feed 2</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <h5 class="card-title display-4">Welcome {{ user.username }}!</h5>
            <img src="{% url 'camera:face_detect' %}" alt="error">
            <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
        </div>
        {% else %}
        <h2>Register or Login if you'd like to</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

core/camera/templates/camera/index.html
{% extends "camera/sidebar.html" %}
{% block body_block %}
<br>
<div class="container">
    <div class="card text-center">
        {% if user.is_authenticated %}
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs" id="modeNav">
                <li class="nav-item">
                    <a class="nav-link active" href="#" id="vanillaBtn">Vanilla Feed</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'detect_on'%}" id="detectBtn">AI Feed 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1" id="smartBtn">AI Feed 2</a>
                </li>
            </ul>
        </div>
        <div class="card-body placeImage">
            <h5 class="card-title display-4">Welcome {{ user.username }}!</h5>
            <img src="{% url 'camera:camera_feed' %}" alt="error" id="vanillaImg">
            <br>
            
        </div>
        {% else %}
        <h2>Register or Login if you'd like to</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

core/camera/templates/camera/login.html
{% extends 'camera/sidebar.html' %}
{% block body_block %}
<div class="container">
    <br>
    <div class="jumbotron">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
        </ul>
        {% endif %}
        <h1>Login here :</h1>
        <form method="post" action="{% url 'camera:user_login' %}">
            {% csrf_token %}

            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username">
            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Password">
            <input type="submit" name="" value="Login">
        </form>
    </div>
</div>
{% endblock %}

core/camera/templates/camera/registration.html
{% extends "camera/sidebar.html" %}
{% load static %}
{% block body_block %}
<div class="container">
    <br>
    <div class="jumbotron">
        {% if registered %}
        <h1>Thank you for registering!</h1>
        {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>

        {% endif %}
    </div>
</div>
{% endblock %}

core/camera/templates/camera/sidebar.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        #wrapper {
            overflow-x: hidden;
        }

        #sidebar-wrapper {
            min-height: 100vh;
            margin-left: -15rem;
            -webkit-transition: margin .25s ease-out;
            -moz-transition: margin .25s ease-out;
            -o-transition: margin .25s ease-out;
            transition: margin .25s ease-out;
        }

        #sidebar-wrapper .sidebar-heading {
            padding: 0.875rem 1.25rem;
            font-size: 1.2rem;
        }

        #sidebar-wrapper .list-group {
            width: 15rem;
        }

        #page-content-wrapper {
            min-width: 100vw;
        }

        #wrapper.toggled #sidebar-wrapper {
            margin-left: 0;
        }

        @media (min-width: 768px) {
            #sidebar-wrapper {
                margin-left: 0;
            }

            #page-content-wrapper {
                min-width: 0;
                width: 100%;
            }

            #wrapper.toggled #sidebar-wrapper {
                margin-left: -15rem;
            }
        }
    </style>
</head>

<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Computer Vision</div>
            <div class="list-group list-group-flush">
                <a href="{% url 'index' %}" class="list-group-item list-group-item-action bg-light">Dashboard</a>
                <a href="{% url 'camera:register' %}"
                    class="list-group-item list-group-item-action bg-light">Register</a>
                <!-- <a href="#" class="list-group-item list-group-item-action bg-light">Overview</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Events</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Profile</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Status</a> -->
            </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}" class="nav-link active">Logout</a>
                            {% else %}
                            <a class="nav-link active" href="{% url 'camera:user_login' %}">Login</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container-fluid">
                {% block body_block %}
                {% endblock %}
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->


</body>

</html>